## Pandas Day 01

In [1]:
#import libraries
import pandas as pd
import numpy as np

In [4]:
# import data as csv
df = pd.read_csv('population_pakistan.csv')
df.head()

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48

In [7]:
#write the data
df.to_excel('population_pakistan.xlsx', index=False)

## pandas tips and tricks

In [8]:
#print the data variables or data in terminal
print(df)

     PROVINCE                   DIVISION                   DISTRICT  \
0      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
1      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
2      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
3      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
4      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
..        ...                        ...                        ...
523  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT
524  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT
525  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT
526  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT
527  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT

            SUB DIVISION  AREA (sq.km)  ALL SEXES (RURAL)  MALE (RURAL)  \
0    BAHAWALNAGAR TEHSIL        1729.0             619550        316864
1       CHISHTIAN TEHSIL        1500.0             540342        273788
2      FORT ABBAS TEHSIL        2536.0             361240        182655
3      HAROONABAD TEHSIL        1295.0             382115        192278
4     MINCHINABAD TEHSIL        1818.0             452723        231506
..                   ...           ...                ...           ...
523     SARAROGHA TEHSIL         813.0              98180         51479
524      SERWEKAI TEHSIL         398.0              54540         28695
525        TIARZA TEHSIL         734.0              45156         23649
526    TOI KHULLA TEHSIL         567.0              50413         27462
527          WANA TEHSIL        2315.0             153156         81342

     FEMALE (RURAL)  TRANSGENDER (RURAL)  SEX RATIO (RURAL)  ...  \
0            302644                   42             104.70  ...
1            266500                   54             102.73  ...
2            178541                   44             102.30  ...
3            189808                   29             101.30  ...
4            221178                   39             104.67  ...
..              ...                  ...                ...  ...
523           46694                    7             110.25  ...
524           25844                    1             111.03  ...
525           21507                    0             109.96  ...
526           22947                    4             119.68  ...
527           71796                   18             113.30  ...

     POPULATION 1998 (RURAL)  ANNUAL GROWTH RATE (RURAL)  ALL SEXES (URBAN)  \
0                     407768                        2.22             193840
1                     395983                        1.65             149424
2                     250959                        1.93              61528
3                     297343                        1.33             142600
4                     316593                        1.90              72294
..                       ...                         ...                ...
523                    72063                        1.64                  0
524                    31472                        2.93                  0
525                    37708                        0.95                  0
526                    36508                        1.71                  0
527                    90772                        2.79                  0

     MALE (URBAN)  FEMALE (URBAN)  TRANSGENDER (URBAN)  SEX RATIO (URBAN)  \
0           98391           95402                   47             103.13
1           75546           73851                   27             102.30
2           31360           30150                   18             104.01
3           71345           71236                   19             100.15
4           36694           35590                   10             103.10
..            ...             ...                  ...                ...
523             0               0                    0               0.00
524             0               0                    0               0.00
525             0               0                    0               0.00
526             0               0                    0               0.00
527             0               0                    0               0.00

     AVG HOUSEHOLD SIZE (URBAN)  POPULATION 1998 (URBAN)  \
0                          6.02                   133785
1                          6.01                   102287
2                          6.00                    34637
3                          6.02                    84424
4                          6.34                    37668
..                          ...                      ...
523                        0.00                        0
524                        0.00                        0
525                        0.00                        0
526                        0.00                        0
527                        0.00                        0

     ANNUAL GROWTH RATE (URBAN)
0                          1.97
1                          2.01
2                          3.06
3                          2.79
4                          3.48
..                          ...
523                        0.00
524                        0.00
525                        0.00
526                        0.00
527                        0.00

[528 rows x 21 columns]

In [9]:
#how does the data look like
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROVINCE                    528 non-null    object
 1   DIVISION                    528 non-null    object
 2   DISTRICT                    528 non-null    object
 3   SUB DIVISION                528 non-null    object
 4   AREA (sq.km)                528 non-null    float64
 5   ALL SEXES (RURAL)           528 non-null    int64
 6   MALE (RURAL)                528 non-null    int64
 7   FEMALE (RURAL)              528 non-null    int64
 8   TRANSGENDER (RURAL)         528 non-null    int64
 9   SEX RATIO (RURAL)           528 non-null    float64
 10  AVG HOUSEHOLD SIZE (RURAL)  528 non-null    float64
 11  POPULATION 1998 (RURAL)     528 non-null    int64
 12  ANNUAL GROWTH RATE (RURAL)  528 non-null    float64
 13  ALL SEXES (URBAN)           528 non-null    int64
 14  MALE (URBAN)                528 non-null    int64
 15  FEMALE (URBAN)              528 non-null    int64
 16  TRANSGENDER (URBAN)         528 non-null    int64
 17  SEX RATIO (URBAN)           528 non-null    float64
 18  AVG HOUSEHOLD SIZE (URBAN)  528 non-null    float64
 19  POPULATION 1998 (URBAN)     528 non-null    int64
 20  ANNUAL GROWTH RATE (URBAN)  528 non-null    float64
dtypes: float64(7), int64(10), object(4)
memory usage: 86.8+ KB

In [10]:
#checking the first rows of the data

In [12]:
#checking the last rows of the data
df.tail()

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
523,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SARAROGHA TEHSIL,813.0,98180,51479,46694,7,110.25,...,72063,1.64,0,0,0,0,0.0,0.0,0,0.0
524,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SERWEKAI TEHSIL,398.0,54540,28695,25844,1,111.03,...,31472,2.93,0,0,0,0,0.0,0.0,0,0.0
525,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TIARZA TEHSIL,734.0,45156,23649,21507,0,109.96,...,37708,0.95,0,0,0,0,0.0,0.0,0,0.0
526,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,119.68,...,36508,1.71,0,0,0,0,0.0,0.0,0,0.0
527,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,WANA TEHSIL,2315.0,153156,81342,71796,18,113.30,...,90772,2.79,0,0,0,0,0.0,0.0,0,0.0

In [13]:
#checking the sample of the data
df.sample(5)

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
233,SINDH,Mirpurkhas Division,MIRPUR KHAS DISTRICT,MIRPUR KHAS TALUKA,24.0,26155,13441,12708,6,105.77,...,11735,4.30,234133,120114,113984,35,105.38,5.68,189671,1.11
319,BALOCHISTAN,Makran Division,GWADAR DISTRICT,JIWANI TEHSIL,454.0,8423,4340,4083,0,106.29,...,5716,2.06,18268,9511,8753,4,108.66,6.10,14072,1.38
15,PUNJAB,D.G.KHAN DIVISION,DERA GHAZI KHAN DISTRICT,DE-EXCLUDED AREA D.G KHAN,5339.0,212652,109429,103213,10,106.02,...,126198,2.78,0,0,0,0,0.00,0.00,0,0.00
234,SINDH,Mirpurkhas Division,MIRPUR KHAS DISTRICT,SHUJAABAD TALUKA,396.0,147733,76277,71433,23,106.78,...,88634,2.72,21000,10828,10168,4,106.49,4.90,10149,3.89
279,SINDH,Sukkur Division,SUKKUR DISTRICT,SUKKUR CITY TALUKA,250.0,0,0,0,0,0.00,...,2833,0.00,231459,118916,112511,32,105.69,5.46,212242,0.46

In [14]:
#checking the statistical summary of the data
df.describe()

,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),AVG HOUSEHOLD SIZE (RURAL),POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
count,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000
mean,1492.005871,2.462780e+05,1.252757e+05,1.209841e+05,18.174242,98.982614,6.277064,1.674280e+05,3.124792,1.408635e+05,7.284339e+04,6.799787e+04,22.276515,75.411269,4.406402,8.014457e+04,1.920814
std,2039.453778,2.711898e+05,1.375630e+05,1.337169e+05,25.522248,26.812660,2.074947,1.783890e+05,9.577872,3.512463e+05,1.823492e+05,1.688725e+05,66.068127,49.687341,2.948336,2.023120e+05,2.098908
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,425.000000,5.093450e+04,2.712725e+04,2.397900e+04,1.000000,101.105000,5.700000,3.527350e+04,1.440000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
50%,882.000000,1.652410e+05,8.413450e+04,8.204400e+04,10.000000,105.285000,6.310000,1.172065e+05,2.030000,4.325450e+04,2.198000e+04,2.099900e+04,3.000000,103.195000,5.755000,2.129800e+04,1.855000
75%,1734.250000,3.129112e+05,1.605022e+05,1.522190e+05,25.000000,108.347500,7.200000,2.130542e+05,2.812500,1.178148e+05,6.030175e+04,5.746525e+04,19.000000,107.040000,6.340000,6.542225e+04,2.985000
max,18374.000000,2.297375e+06,1.172995e+06,1.124167e+06,213.000000,139.380000,12.430000,1.044035e+06,100.000000,3.653616e+06,1.905921e+06,1.746900e+06,795.000000,297.810000,10.060000,2.075867e+06,19.780000

In [ ]:
#now checking the row which has the maximum area
df.loc[df['AREA (sq.km)'].idxmax()]

PROVINCE                                   PUNJAB
DIVISION                      BAHAWALPUR DIVISION
DISTRICT                      BAHAWALPUR DISTRICT
SUB DIVISION                        YAZMAN TEHSIL
AREA (sq.km)                              18374.0
ALL SEXES (RURAL)                          564422
MALE (RURAL)                               288761
FEMALE (RURAL)                             275612
TRANSGENDER (RURAL)                            49
SEX RATIO (RURAL)                          104.77
AVG HOUSEHOLD SIZE (RURAL)                   6.41
POPULATION 1998 (RURAL)                    385770
ANNUAL GROWTH RATE (RURAL)                   2.02
ALL SEXES (URBAN)                           48883
MALE (URBAN)                                24884
FEMALE (URBAN)                              23995
TRANSGENDER (URBAN)                             4
SEX RATIO (URBAN)                           103.7
AVG HOUSEHOLD SIZE (URBAN)                   6.18
POPULATION 1998 (URBAN)                     21028
ANNUAL GROWTH RATE (URBAN)                   4.53
Name: 10, dtype: object

In [19]:
#checking the row which has the minimum area
df.loc[df['AREA (sq.km)'].idxmin()]

PROVINCE                                   BALOCHISTAN
DIVISION                                 Zhob Division
DISTRICT                      KILLA SAIFULLAH DISTRICT
SUB DIVISION                         BADINI SUB-TEHSIL
AREA (sq.km)                                       0.0
ALL SEXES (RURAL)                                15345
MALE (RURAL)                                      8720
FEMALE (RURAL)                                    6625
TRANSGENDER (RURAL)                                  0
SEX RATIO (RURAL)                               131.62
AVG HOUSEHOLD SIZE (RURAL)                        6.89
POPULATION 1998 (RURAL)                           6583
ANNUAL GROWTH RATE (RURAL)                        4.55
ALL SEXES (URBAN)                                    0
MALE (URBAN)                                         0
FEMALE (URBAN)                                       0
TRANSGENDER (URBAN)                                  0
SEX RATIO (URBAN)                                  0.0
AVG HOUSEHOLD SIZE (URBAN)                         0.0
POPULATION 1998 (URBAN)                              0
ANNUAL GROWTH RATE (URBAN)                         0.0
Name: 393, dtype: object

In [21]:
# checking the area with maximum transgender population both in rural and urban areas
max_trans_rural = df.loc[df['TRANSGENDER (RURAL)'].idxmax()]
max_trans_urban = df.loc[df['TRANSGENDER (URBAN)'].idxmax()]
print("Max Transgender (Rural):")
print(max_trans_rural)
print("\nMax Transgender (Urban):")
print(max_trans_urban)

Max Transgender (Rural):
PROVINCE                                    KPK
DIVISION                      PESHAWAR DIVISION
DISTRICT                      PESHAWAR DISTRICT
SUB DIVISION                    PESHAWAR TEHSIL
AREA (sq.km)                             1257.0
ALL SEXES (RURAL)                       2297375
MALE (RURAL)                            1172995
FEMALE (RURAL)                          1124167
TRANSGENDER (RURAL)                         213
SEX RATIO (RURAL)                        104.34
AVG HOUSEHOLD SIZE (RURAL)                 8.74
POPULATION 1998 (RURAL)                 1044035
ANNUAL GROWTH RATE (RURAL)                 4.23
ALL SEXES (URBAN)                       1969823
MALE (URBAN)                            1025010
FEMALE (URBAN)                           944401
TRANSGENDER (URBAN)                         412
SEX RATIO (URBAN)                        108.54
AVG HOUSEHOLD SIZE (URBAN)                 7.97
POPULATION 1998 (URBAN)                  982816
ANNUAL GROWTH RATE (URBAN)                 3.72
Name: 455, dtype: object

Max Transgender (Urban):
PROVINCE                                  PUNJAB
DIVISION                         LAHORE DIVISION
DISTRICT                         LAHORE DISTRICT
SUB DIVISION                  LAHORE CITY TEHSIL
AREA (sq.km)                               214.0
ALL SEXES (RURAL)                              0
MALE (RURAL)                                   0
FEMALE (RURAL)                                 0
TRANSGENDER (RURAL)                            0
SEX RATIO (RURAL)                            0.0
AVG HOUSEHOLD SIZE (RURAL)                   0.0
POPULATION 1998 (RURAL)                   143532
ANNUAL GROWTH RATE (RURAL)                 100.0
ALL SEXES (URBAN)                        3653616
MALE (URBAN)                             1905921
FEMALE (URBAN)                           1746900
TRANSGENDER (URBAN)                          795
SEX RATIO (URBAN)                          109.1
AVG HOUSEHOLD SIZE (URBAN)                  6.25
POPULATION 1998 (URBAN)                  2075867
ANNUAL GROWTH RATE (URBAN)                  3.01
Name: 71, dtype: object

In [22]:
# checking the area with minimum transgender population both in rural and urban areas
min_trans_rural = df.loc[df['TRANSGENDER (RURAL)'].idxmin()]
min_trans_urban = df.loc[df['TRANSGENDER (URBAN)'].idxmin()]
print("Min Transgender (Rural):")
print(min_trans_rural)
print("\nmin Transgender (Urban):")
print(min_trans_urban)

Min Transgender (Rural):
PROVINCE                                      PUNJAB
DIVISION                         BAHAWALPUR DIVISION
DISTRICT                         BAHAWALPUR DISTRICT
SUB DIVISION                  BAHAWALPUR CITY TEHSIL
AREA (sq.km)                                  1490.0
ALL SEXES (RURAL)                                  0
MALE (RURAL)                                       0
FEMALE (RURAL)                                     0
TRANSGENDER (RURAL)                                0
SEX RATIO (RURAL)                                0.0
AVG HOUSEHOLD SIZE (RURAL)                       0.0
POPULATION 1998 (RURAL)                        62916
ANNUAL GROWTH RATE (RURAL)                       0.0
ALL SEXES (URBAN)                             682116
MALE (URBAN)                                  350186
FEMALE (URBAN)                                331842
TRANSGENDER (URBAN)                               88
SEX RATIO (URBAN)                             105.53
AVG HOUSEHOLD SIZE (URBAN)                      5.91
POPULATION 1998 (URBAN)                       356626
ANNUAL GROWTH RATE (URBAN)                      3.47
Name: 6, dtype: object

min Transgender (Urban):
PROVINCE                                         PUNJAB
DIVISION                              D.G.KHAN DIVISION
DISTRICT                       DERA GHAZI KHAN DISTRICT
SUB DIVISION                  DE-EXCLUDED AREA D.G KHAN
AREA (sq.km)                                     5339.0
ALL SEXES (RURAL)                                212652
MALE (RURAL)                                     109429
FEMALE (RURAL)                                   103213
TRANSGENDER (RURAL)                                  10
SEX RATIO (RURAL)                                106.02
AVG HOUSEHOLD SIZE (RURAL)                         7.35
POPULATION 1998 (RURAL)                          126198
ANNUAL GROWTH RATE (RURAL)                         2.78
ALL SEXES (URBAN)                                     0
MALE (URBAN)                                          0
FEMALE (URBAN)                                        0
TRANSGENDER (URBAN)                                   0
SEX RATIO (URBAN)                                   0.0
AVG HOUSEHOLD SIZE (URBAN)                          0.0
POPULATION 1998 (URBAN)                               0
ANNUAL GROWTH RATE (URBAN)                          0.0
Name: 15, dtype: object